name: Generate and Update API Docs

on:
  workflow_dispatch: # Cho phép chạy thủ công
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    # Cấp quyền ghi để push commit
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Markdown API documentation for all services
        run: |
          # Tạo thư mục docs tổng
          mkdir -p ./docs
          
          echo "Đang tạo docs cho code-payment-service..."
          npx @openapitools/openapi-generator-cli generate -i https://code-payment-service.20206205.tech/code-payment-service/docs-json -g markdown -o ./docs/code-payment-service

          echo "Đang tạo docs cho code-document-service..."
          npx @openapitools/openapi-generator-cli generate -i http://134.185.92.211/code-document-service/openapi.json -g markdown -o ./docs/code-document-service

          echo "Đang tạo docs cho code-persona-service..."
          npx @openapitools/openapi-generator-cli generate -i http://134.185.92.211/code-persona-service/openapi.json -g markdown -o ./docs/code-persona-service

          echo "Đang tạo docs cho code-conversation-service..."
          npx @openapitools/openapi-generator-cli generate -i http://134.185.92.211/code-conversation-service/docs-json -g markdown -o ./docs/code-conversation-service

          echo "Đang tạo docs cho code-chatbot-service..."
          npx @openapitools/openapi-generator-cli generate -i http://134.185.92.211/code-chatbot-service/openapi.json -g markdown -o ./docs/code-chatbot-service

      - name: Check for changes and Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Đổi đường dẫn add thành thư mục docs mới
          git add ./docs
          
          # Kiểm tra và commit nếu có sự thay đổi
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: auto-update API documentation for all services" && git push)